const STATUS_OK = 200;
const NOT_FOUND = 404;
const BAD_REQUEST = 400;
const ALREADY_EXISTS = 401;
const SOMETHING_WENT_WRONG = 500;

module.exports = {
  STATUS_OK,
  NOT_FOUND,
  BAD_REQUEST,
  ALREADY_EXISTS,
  SOMETHING_WENT_WRONG,
};